//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBL3_MVC.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seat
    {
        public string SeatID { get; set; }
        public string ScheduleID { get; set; }
        public int SeatNumber { get; set; }
        public double Price { get; set; }
        public bool Status { get; set; }
        public string BillID { get; set; }
    
        public virtual Bill Bill { get; set; }
        public virtual Schedule Schedule { get; set; }
    }
}
